# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TheAsp
subtitle: Andrew Phillips
email: theasp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal web page for Andrew Phillips
baseurl: "" # the subpath of your site, e.g. /blog
logo: "/images/andrew.svg"
url: "https://theasp.github.io" # the base hostname & protocol for your site
timezone: Etc/UTC

# Build settings
markdown: kramdown
